In [3]:
import numpy as np
from scipy.spatial import Delaunay
from plotly import graph_objects

In [4]:
from plotly.figure_factory import create_trisurf

In [35]:
u = np.linspace(0,1, 5)
v = np.linspace(0,1, 5)
u,v = np.meshgrid(u,v)
u = u.flatten()
v = v.flatten()


In [36]:
print(u.shape,v.shape)

(25,) (25,)


In [47]:
x = u
y = v
z = 0*x

In [44]:
print(x.shape)

(25,)


In [48]:
points2D = np.vstack([u,v]).T
tri = Delaunay(points2D)
simplices = tri.simplices

In [40]:
print(simplices)

[[ 1  5  0]
 [ 5  1  6]
 [15 21 20]
 [21 15 16]
 [11  5  6]
 [ 5 11 10]
 [15 11 16]
 [11 15 10]
 [ 9  3  4]
 [ 3  9  8]
 [ 7 11  6]
 [11  7 12]
 [ 1  7  6]
 [ 7  1  2]
 [ 7  3  8]
 [ 3  7  2]
 [23 19 24]
 [19 23 18]
 [17 11 12]
 [11 17 16]
 [17 21 16]
 [21 17 22]
 [23 17 18]
 [17 23 22]
 [13  7  8]
 [ 7 13 12]
 [17 13 18]
 [13 17 12]
 [ 9 13  8]
 [13  9 14]
 [13 19 18]
 [19 13 14]]


In [49]:
# Create a figure
fig1 = create_trisurf(x=x, y=y, z=z, colormap="Rainbow",
                      simplices=simplices)

PlotlyError: Incorrect relation between vmin and vmax. The vmin value cannot be bigger than or equal to the value of vmax.

In [42]:
fig1.show()